# Generated by Django 6.0.7 on 2026-08-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_communitygroup_grouppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community_posts/video'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_posts/image'),
        ),
    ]
